/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/dashboard/BarChart.vue')['default']
    BarnVisualization: typeof import('./src/components/BarnVisualization.vue')['default']
    BatchImportDialog: typeof import('./src/components/cattle/BatchImportDialog.vue')['default']
    BatchTransferDialog: typeof import('./src/components/cattle/BatchTransferDialog.vue')['default']
    CattleCard: typeof import('./src/components/cattle/CattleCard.vue')['default']
    CattleDetailDialog: typeof import('./src/components/cattle/CattleDetailDialog.vue')['default']
    CattleFormDialog: typeof import('./src/components/cattle/CattleFormDialog.vue')['default']
    ChartCard: typeof import('./src/components/dashboard/ChartCard.vue')['default']
    DashboardConfigDialog: typeof import('./src/components/dashboard/DashboardConfigDialog.vue')['default']
    DashboardLayout: typeof import('./src/components/dashboard/DashboardLayout.vue')['default']
    DataExportDialog: typeof import('./src/components/dashboard/DataExportDialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    GaugeChart: typeof import('./src/components/dashboard/GaugeChart.vue')['default']
    PendingTasksCard: typeof import('./src/components/dashboard/PendingTasksCard.vue')['default']
    PieChart: typeof import('./src/components/dashboard/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/dashboard/StatCard.vue')['default']
    TrendChart: typeof import('./src/components/dashboard/TrendChart.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
