FROM alpine:latest

RUN apk add --no-cache nodejs npm

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN if [ -f "package.json" ] && grep -q '"build"' package.json; then npm run build; fi

EXPOSE 3014

CMD ["npm", "start"]
