filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/app/backend-1/*.log
    - /var/log/app/backend-2/*.log
  fields:
    service: backend
    environment: production
  fields_under_root: true
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - /var/log/app/nginx/*.log
  fields:
    service: nginx
    environment: production
  fields_under_root: true

- type: docker
  enabled: true
  containers.ids:
    - "*"
  containers.path: "/var/lib/docker/containers"
  containers.stream: "all"

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "cattle-management-%{+yyyy.MM.dd}"

setup.template.name: "cattle-management"
setup.template.pattern: "cattle-management-*"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644