global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'cattle-management-prod'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Backend API metrics
  - job_name: 'cattle-backend'
    static_configs:
      - targets: ['backend:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres-master'
    static_configs:
      - targets: ['postgres-master:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'postgres-slave'
    static_configs:
      - targets: ['postgres-slave:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis-master'
    static_configs:
      - targets: ['redis-master:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'redis-slave'
    static_configs:
      - targets: ['redis-slave:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9114']
    scrape_interval: 30s
    metrics_path: /metrics

  # Application-specific metrics
  - job_name: 'cattle-app-metrics'
    static_configs:
      - targets: ['backend:3000']
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'backend:3000'
        - 'frontend:80'
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 5s

# Remote write configuration for long-term storage
remote_write:
  - url: "http://prometheus-remote-storage:9201/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true