global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 后端API服务监控
  - job_name: 'backend-api'
    static_configs:
      - targets: 
        - 'backend-1:3000'
        - 'backend-2:3000'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: 
        - 'postgres-master:5432'
        - 'postgres-slave:5432'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: 
        - 'redis-master:6379'
        - 'redis-slave:6379'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # 节点监控 (如果部署了node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker容器监控 (如果部署了cadvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s