version: '3.8'
services:
  api-gateway:
    image: microservices_api-gateway_opt
    container_name: api-gateway-opt-container
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - microservices-network
    restart: unless-stopped
  base-service:
    image: microservices_base-service_opt
    container_name: base-service-opt-container
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - microservices-network
    restart: unless-stopped
  cattle-service:
    image: microservices_cattle-service_opt
    container_name: cattle-service-opt-container
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    networks:
      - microservices-network
    restart: unless-stopped
  health-service:
    image: microservices_health-service_opt
    container_name: health-service-opt-container
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
    networks:
      - microservices-network
    restart: unless-stopped
  feeding-service:
    image: microservices_feeding-service_opt
    container_name: feeding-service-opt-container
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
    networks:
      - microservices-network
    restart: unless-stopped
  equipment-service:
    image: microservices_equipment-service_opt
    container_name: equipment-service-opt-container
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
    networks:
      - microservices-network
    restart: unless-stopped
  procurement-service:
    image: microservices_procurement-service_opt
    container_name: procurement-service-opt-container
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
    networks:
      - microservices-network
    restart: unless-stopped
  sales-service:
    image: microservices_sales-service_opt
    container_name: sales-service-opt-container
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - PORT=3008
    networks:
      - microservices-network
    restart: unless-stopped
  material-service:
    image: microservices_material-service_opt
    container_name: material-service-opt-container
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - PORT=3009
    networks:
      - microservices-network
    restart: unless-stopped
  notification-service:
    image: microservices_notification-service_opt
    container_name: notification-service-opt-container
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
    networks:
      - microservices-network
    restart: unless-stopped
  file-service:
    image: microservices_file-service_opt
    container_name: file-service-opt-container
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=development
      - PORT=3011
    networks:
      - microservices-network
    restart: unless-stopped
  monitoring-service:
    image: microservices_monitoring-service_opt
    container_name: monitoring-service-opt-container
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=development
      - PORT=3012
    networks:
      - microservices-network
    restart: unless-stopped
  news-service:
    image: microservices_news-service_opt
    container_name: news-service-opt-container
    ports:
      - "3013:3013"
    environment:
      - NODE_ENV=development
      - PORT=3013
    networks:
      - microservices-network
    restart: unless-stopped
networks:
  microservices-network:
    driver: bridge
