networks:
  microservices-network:
    driver: bridge

services:
  # 认证服务
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=cattle_management_dev
      - DB_USER=cattle_user
      - DB_PASSWORD=dianxin99
      - JWT_SECRET=your-development-jwt-secret-key
    networks:
      - microservices-network
    restart: unless-stopped
  base-service:
    build:
      context: ./base-service
      dockerfile: Dockerfile.simple
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - microservices-network
    restart: unless-stopped

  cattle-service:
    build:
      context: ./cattle-service
      dockerfile: Dockerfile.simple
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    networks:
      - microservices-network
    restart: unless-stopped

  health-service:
    build:
      context: ./health-service
      dockerfile: Dockerfile.simple
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
    networks:
      - microservices-network
    restart: unless-stopped

  feeding-service:
    build:
      context: ./feeding-service
      dockerfile: Dockerfile.simple
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
    networks:
      - microservices-network
    restart: unless-stopped

  equipment-service:
    build:
      context: ./equipment-service
      dockerfile: Dockerfile.simple
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
    networks:
      - microservices-network
    restart: unless-stopped

  procurement-service:
    build:
      context: ./procurement-service
      dockerfile: Dockerfile.simple
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
    networks:
      - microservices-network
    restart: unless-stopped

  sales-service:
    build:
      context: ./sales-service
      dockerfile: Dockerfile.simple
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - PORT=3008
    networks:
      - microservices-network
    restart: unless-stopped

  material-service:
    build:
      context: ./material-service
      dockerfile: Dockerfile.simple
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - PORT=3009
    networks:
      - microservices-network
    restart: unless-stopped

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.simple
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
    networks:
      - microservices-network
    restart: unless-stopped

  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile.simple
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=development
      - PORT=3011
    networks:
      - microservices-network
    restart: unless-stopped

  monitoring-service:
    build:
      context: ./monitoring-service
      dockerfile: Dockerfile.simple
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=development
      - PORT=3012
    networks:
      - microservices-network
    restart: unless-stopped

  news-service:
    build:
      context: ./news-service
      dockerfile: Dockerfile.simple
    ports:
      - "3013:3013"
    environment:
      - NODE_ENV=development
      - PORT=3013
    networks:
      - microservices-network
    restart: unless-stopped