services:
  # 数据库服务
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cattle_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dianxin99
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - microservices-network

  # Redis服务
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network

  # 单体后端服务（共享数据库）
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3100:3000"  # 内部端口3000，外部映射3100避免冲突
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=cattle_management
      - DB_USER=postgres
      - DB_PASSWORD=dianxin99
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-jwt-secret-key
      - PORT=3000
    depends_on:
      - postgres
      - redis
    networks:
      - microservices-network
    restart: unless-stopped

  # API网关
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_SERVICE_URL=http://backend:3000
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 用户认证服务
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=dianxin99
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - postgres
      - redis
    networks:
      - microservices-network
    restart: unless-stopped

  # 基地管理服务
  base-service:
    build:
      context: ./base-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 牛只管理服务
  cattle-service:
    build:
      context: ./cattle-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 健康管理服务
  health-service:
    build:
      context: ./health-service
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 饲养管理服务
  feeding-service:
    build:
      context: ./feeding-service
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 设备管理服务
  equipment-service:
    build:
      context: ./equipment-service
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 采购管理服务
  procurement-service:
    build:
      context: ./procurement-service
      dockerfile: Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 销售管理服务
  sales-service:
    build:
      context: ./sales-service
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 物料管理服务
  material-service:
    build:
      context: ./material-service
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - BACKEND_URL=http://backend:3000/api/v1
    depends_on:
      - redis
      - backend
    networks:
      - microservices-network
    restart: unless-stopped

  # 通知服务
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      - redis
      - auth-service
    networks:
      - microservices-network
    restart: unless-stopped

  # 文件服务
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=http://auth-service:3001
    volumes:
      - file_uploads:/app/uploads
    depends_on:
      - auth-service
    networks:
      - microservices-network
    restart: unless-stopped

  # 监控服务
  monitoring-service:
    build:
      context: ./monitoring-service
      dockerfile: Dockerfile
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:3001
    depends_on:
      - redis
      - auth-service
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  file_uploads:

networks:
  microservices-network:
    driver: bridge