version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - microservices-network

  base-service:
    build:
      context: ./base-service
      dockerfile: Dockerfile.simple
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - microservices-network

  cattle-service:
    build:
      context: ./cattle-service
      dockerfile: Dockerfile.simple
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
    networks:
      - microservices-network

  health-service:
    build:
      context: ./health-service
      dockerfile: Dockerfile.simple
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
    networks:
      - microservices-network

  feeding-service:
    build:
      context: ./feeding-service
      dockerfile: Dockerfile.simple
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
    networks:
      - microservices-network

  equipment-service:
    build:
      context: ./equipment-service
      dockerfile: Dockerfile.simple
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
    networks:
      - microservices-network

  procurement-service:
    build:
      context: ./procurement-service
      dockerfile: Dockerfile.simple
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
      - PORT=3007
    networks:
      - microservices-network

  sales-service:
    build:
      context: ./sales-service
      dockerfile: Dockerfile.simple
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=development
      - PORT=3008
    networks:
      - microservices-network

  material-service:
    build:
      context: ./material-service
      dockerfile: Dockerfile.simple
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - PORT=3009
    networks:
      - microservices-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile.simple
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
    networks:
      - microservices-network

  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile.simple
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=development
      - PORT=3011
    networks:
      - microservices-network

  monitoring-service:
    build:
      context: ./monitoring-service
      dockerfile: Dockerfile.simple
    ports:
      - "3012:3012"
    environment:
      - NODE_ENV=development
      - PORT=3012
    networks:
      - microservices-network

  news-service:
    build:
      context: ./news-service
      dockerfile: Dockerfile.simple
    ports:
      - "3013:3013"
    environment:
      - NODE_ENV=development
      - PORT=3013
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
